spring.application.name=forum-hub
spring.datasource.url=jdbc:postgresql://localhost:5432/forumhub3
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Contexto da aplicacao
server.servlet.context-path=/dev-forumhub/v3/api

# Outras configs uteis
server.error.include-stacktrace=never
logging.level.org.springframework.security=DEBUG