ALTER TABLE users
    ALTER COLUMN role DROP DEFAULT;

ALTER TABLE users
ALTER COLUMN role TYPE VARCHAR(50)
USING role::text;

DROP TYPE user_role;

ALTER TABLE users
    ALTER COLUMN role SET DEFAULT 'ROLE_STUDENT';